Includes/renderer.cpp
Includes/renderer.h
main.cpp

@ChrisDerWahre and @gxtx reported that overscan made parts of the menu unreadable.
Hopefully this PR fixes those problems. Initial testing suggests they do.

Fix overscan issues

---

main.cpp

XVideoSetMode() will be removed from XboxCRTEntry() in XboxDev/nxdk-pdclib#3.
This PR will make sure we comply with that change and can continue operating as per usual.

video: Update to comply with nxdk changes

---

Includes/ftpConnection.cpp
Includes/ftpConnection.h
Includes/ftpServer.cpp
Includes/ftpServer.h
Includes/outputLine.cpp
Includes/subsystems.cpp

During work targeting @thrimbor's NIC driver fixes, some oddities were identified and corrected.
- The framebuffer is now allocated
- FTP connections no longer kill themselves - the FTP server kills them instead
- FTP connections now have a decent destructor
- `outputLine` no longer requires SDL in the non-nxdk build

Backports from the thrimbornet branch

---

main.cpp

CPU is probably better used in other places than simply polling for input events.
Nice side effect of this change is that FTP transfer speeds skyrocketed from ~130KiB/s to ~1.3MiB/s during my (limited) testing.

main: Stop hogging CPU in main thread

---

Makefile

build: Don't override NXDK_DIR if already set

---

Includes/networking.cpp

While it isn't in the issues section, NevoX currently has an issue where in case you boot it with no internet connection, it hangs waiting for the DHCP server settings. This is caused by a line in the networking.cpp file that runs `NtYieldExecution()` while waiting. This PR adds a 7-second timeout to that loop, and it would probably be a good idea to make the given time adjustable through the config.json file. This can be implemented in a future PR.

networking: Timeout the DHCP server

---

Includes/subsystems.cpp

Add discussed on discord, for some reason initialising the gamecontroller subsystem before the network subsystem can cause a hang in some rare cases.

Init: Reorder subsystem initialisations

---

Includes/audioMenu.cpp
Includes/audioMenu.hpp
Includes/eeprom.hpp
Includes/settingsMenu.cpp
Includes/settingsMenu.hpp
Includes/videoMenu.cpp
Includes/videoMenu.hpp
Makefile
main.cpp

closes #64 
Slimmer EEPROM handling, simpler audio logic (could  [should?] be improved in the future).

settings: Add EEPROM query template, Audio and Video menus

---

Includes/menu.cpp
Includes/menu.hpp
sampleconfig.json

Adds the ability to provide comma-delimited paths instead of a single path for a `scan` item (so games across multiple partitions can go under one menu item).

Adds ability to parse multiple paths per menu item.

---

Includes/ftpServer.cpp
Includes/ftpServer.h
Includes/networkManager.cpp
Includes/networkManager.h
Includes/networking.cpp
Includes/networking.h
Includes/renderer.h
Includes/subsystems.cpp
Makefile
main.cpp

-  Switches init of the network and network-dependent services to a background thread so a slow DHCP response does not stall entry into the dashboard.
- Adds rendering of the current IP address as an indication that the network is running.
- Simplifies handling of subsystem init failure in `main.cpp` to reduce indentation of the main loop.

Defers network initialization.

---

Includes/findXBE.cpp

Came across some XBEs that do not have any `xbeName` info in the certification header. This change uses the dirname of the `default.xbe` to avoid blank entries in the menu.

Adds fallback name for XBEs without full cert headers.

---

Includes/infoLog.cpp
Includes/infoLog.h
Includes/outputLine.cpp
Includes/renderer.cpp
Includes/renderer.h
Makefile
main.cpp

This PR adds a simple logging overlay that intercepts `outputLine` invocations and displays them on top of rendered content until some timeout elapses (30 frames by default).
Followup enhancements:
- Make the functionality configurable; for non-devs some or most of the `outputLine` info is probably not interesting and it might be useful to modify the background color of the overlay once theming is implemented.
- Provide full log rendering w/ scrolling
- Put a cap on the log size
This is a screenshot of me entering and exiting the first menu item a few times to generate some log text.

Adds log overlay

---

Includes/config.cpp
Includes/config.hpp
Includes/infoLog.cpp
Includes/infoLog.h
main.cpp
sampleconfig.json

Foillowup to #84 to allow the log overlay behavior to be modified via the config file.

Makes log overlay configurable

---

Includes/xbeScanner.cpp
Includes/xbeScanner.h
Makefile

Part one of a proposal to make the XBE scanning process asynchronous. As a followup, I intend to modify `MenuXbe` to make use of this async scanner such that it displays "Scanning..." as its only child until the process is completed. I believe this will improve the latency between NevolutionX launching and the top level menu being displayed in cases where there are a lot of XBEs to scan (e.g., very large F/G partitions).
If this generally makes sense, I'd follow up w/ a further change to move the path splitting from `MenuXbe` into the scanner (just to simplify completion handling) and would change `MenuXbe` to have a non-`execute`able dummy child on construction that will be replaced with a proper child list once scanning is completed. I'd also remove `findXBE.*` since the functionality …

menu: Adds asynchronous XBE scanner.

---

Includes/menu.cpp
Includes/menu.hpp

This builds off of #80 and modifies MenuXbe to use the async scanner.
While paths are being scanned, the menu item will have a non-interactive child that displays `Scanning "path" ...`. Once all paths are scanned, the sorted list of children will be swapped in.

Implements async scanning of XBEs

---

Includes/menu.cpp
Includes/menu.hpp
Includes/subApp.h
Includes/subAppRouter.cpp
Includes/subAppRouter.h
Makefile
main.cpp

This PR adds a notion of subapplications in preparation for adding a full page log viewer.
A SubApp is simply a handler for rendering and controller input. `Menu` is currently the only (and base) sub app, the router allows replacements for the menu to be pushed over the menu so they can handle input in different ways.
This should also pave the way for things like having an in-dash editor (popping a virtual keyboard) or a grid-based XBE launcher as an alternative to the menu list.

Adds subapprouter

---

Includes/menu.cpp
Includes/subApp.h
Includes/subAppRouter.cpp
Includes/subAppRouter.h
main.cpp

Allows `SubApp` instances to opt in to having buttons repeat while being held down (e.g., menus can now be scrolled by holding down the up/down buttons rather than having to tap for each item).
If the input handling changes get merged we can add a followup to make the repeat interval configurable.

Adds button repeating

---

Includes/infoLog.cpp
Includes/infoLog.h
Includes/logViewer.cpp
Includes/logViewer.h
Includes/logViewerMenu.cpp
Includes/logViewerMenu.h
Includes/menu.hpp
Includes/outputLine.cpp
Includes/settingsMenu.cpp
Makefile
main.cpp

Very basic fullscreen log viewer subapp.
Planned enhancements:
- Scrollbar to display position with the log
- Prevent scrolling up past one full screen of the log
- Support for scrolling by page
- Automatic scrolling while the dpad is held down (dependent on #90 )
- Indication that the log is explicitly locked to the bottom and will scroll as new events come in (in case we start using more log messages in the FTP server or some other interesting background thread)

Adds fullscreen log viewer

---

.gitignore

- Ignores the .iso build artifact
- Ignores any local `.gdbinit` files (these are needed for CLion + xemu as a remote GDB host)
- Ignores `.idea/` so any JetBrains editor cruft doesn't get accidentally submitted.

gitignore: Ignores iso files and CLion editor artifacts.

---

CONTRIBUTING.md
githooks/pre-commit

- Adds a pre-commit hook to apply `clang-format` to any source files (outside of `3rdparty`).
- Applies some of the sample hooks that ship with git.
- Adds a note to contributors to opt into using the hook.

Adds pre-commit hook for clang-format.

---

Includes/menu.hpp
Includes/subApp.h
Includes/subAppRouter.cpp
Includes/subAppRouter.h

Changes in preparation for using the right analog stick for a superscroll implementation for #94. This also maps the left analog stick to the dpad inputs so the user can use either to navigate the menu. A nice followup would be to enable the automatic repeat behavior as well, the repeat mechanism would need to be extended to support the virtual  "stick as digital" events.
Note: I don't actually have a controller handy for the next few days so this is a prospective change using a keyboard input in xemu.

input: Adds analog axis handling.

---

githooks/pre-commit

Fixes my silly mistake where deleting a file will cause the pre-commit hook to fail (as it blindly tries to run `clang-format` on a file that no longer exists).

codestyle: Fixes pre-commit behavior on deleted C++ files.

---

Makefile

Based on discussion in XboxDev/nxdk#510

make: Defaults to optimized build if DEBUG is unset.

---

Includes/menu.cpp
Includes/menu.hpp
Includes/xbeScanner.cpp
Includes/xbeScanner.h

Making XBE scanning synchronous until #110 is implemented as the async thread gets starved, leading to multi-minute scan times on a library w/ 160 XBEs.
The downside is that it now takes ~10 extra seconds to get off the initial black screen (presumably this has a direct relationship w/ number of XBEs). The black screen will at least print that a scan is being done so it's not a total user experience disaster :)

menu: Makes XBE scanner synchronous.

---

Includes/menu.cpp
Includes/xbeLauncher.cpp
Includes/xbeLauncher.h
Makefile

- Blanks the framebuffer before exiting the dashboard (see discussion in XboxDev/nxdk/#511)
- Adds a bottleneck for activities that exit the dashboard to allow a future loading screen (in prep for #113 )

menu: Blanks framebuffer before exiting/launching XBEs.

---

Sources/ftpConnection.cpp

Since XboxDev/nxdk@aa0aa27d59c0ff2239fd6ca1344a7407, folder opening requires an extra flag.

ftp: Fix folder browsing

---

.github/workflows/build.yml

I made a slight modification to use NXDK's `bin/activate` script to setup its own build system.
Plus added ability to upload bin folder to artifact without need to extract iso every time.

Update GitHub CI build and add binary folder to artifact

---

Makefile

Decreases bootup time by atleast 0.5 seconds.

make: Remove SDL input delay on startup

---

Sources/xbeScanner.cpp

An issue loading directories/files is experienced when a trailing backslash is not included in the config menu scan path, the dashboard menu result is '<empty>'. The default, sampleconfig.json, includes menu scan paths without a trailing backslash and so it was expected.
related: #74

fix(xbescanner): scan paths missing trailing slashes
