dracc/NevolutionX

main.cpp
This fixes the bug where a games list of more than 4 items wasn't fully reachable.
=> Update list length on redraw

Includes/renderer.cpp, Includes/renderer.h, main.cpp
Needs testing but I believe the logic could work.
=> render: Scroll games list when needed

main.cpp
When in the games list, react on B button press and go back to the main menu.
=> Go back on B press

CMakeLists.txt, Includes/renderer.cpp, Includes/renderer.h, Includes/vector.hpp, main.cpp
Change `int` to `size_t` where so fit.
I also opted to include the CMake changes used in order to find these booboos.
=> hygiene: Don't compare values with differing signedness

Includes/findXBE.cpp
Some games such as Blinx and Forza Motorsport wouldn't show up in the Games list as their headers are bigger than 1000 bytes. These changes ought to fix that.
=> findXBE: Support big headers

Includes/outputLine.h
Fixes compilation with latest nxdk.
=> outputLine: Update path to debug.h

.dir-locals.el
Adds a style config file for `emacs`, helping ensure a uniform code style throughout the project.
=> meta: Emacs style config

Includes/networking.cpp, Includes/networking.h, Includes/subsystems.cpp, Makefile, main.cpp
Set up some primitive networking. Hopefully NXDK will see changes in this area soon rendering these changes broken. But in the meantime, they work well enough for the `ftpserver` branch.
I'm aware some minor cleanup-stuff slipped through and ended up in main.cpp too. I can live with that.
=> Networking

CMakeLists.txt, Includes/ftpConnection.cpp, Includes/ftpConnection.h, Includes/ftpServer.cpp, Includes/ftpServer.h, Makefile, main.cpp
A few known issues;
- Username and password are hard coded
- Not being able to login doesn't really have any effect (:grimacing:)
- LIST and NLST doesn't consider arguments
- PASV not implemented (not really necessary either?)
I do not intend to implement encryption.
=> Implement FTP server

.github/workflows/build.yml
Also add artifact uploading, because why not?
=> ci: Remove CMake build from actions

Includes/ftpConnection.cpp
Don't allow users to do stuff per FTP without signing in first.
Closes #36
=> ftp: Control user auth status

Includes/config.cpp, Includes/config.hpp, Includes/font.h, Includes/ftpConnection.cpp, Includes/ftpServer.cpp, Includes/ftpServer.h, Includes/menu.cpp, main.cpp, sampleconfig.json
=> config: Utilize FTP part of JSON config file

main.cpp
Won't work on Xbox until proper support is added in nxdk.
But when that comes, we're ready.
Closes #46
=> input: Add controller hotplug support

.github/workflows/build.yml
=> ci improvements

Includes/ftpConnection.cpp, Includes/ftpConnection.h
=> FTP: Add command 'execute'

Includes/settingsMenu.cpp, Includes/wipeCache.cpp, Includes/wipeCache.hpp, Makefile
Untested - use at your own risk!
=> Cache wipe (WIP)

Makefile
=> Makefile: Make cp into one command

Includes/menu.cpp, Includes/menu.hpp, main.cpp
Allows faster menu navigation via dpad left & right
=> Adds support for paging in menus.

.gitmodules, Includes/menu.cpp
Addresses #87 by utilizing a natural sort implementation.
=> Applies natural sorting to XBEs

Makefile
Hopefully will make things less prone to merge conflicts. Note that #102 needs to be merged first since it's removing a file and this PR also leaves that file out.
=> Sorts Makefile

Includes/menu.cpp, Includes/menu.hpp
Addresses #94 by allowing the right thumbstick to be used to skip through the list by first letter.
=> Adds "superscroll", allowing XBE lists to be navigated by first character

Includes/config.cpp, Includes/config.hpp, Includes/timing.cpp, Includes/timing.h, Makefile, main.cpp, sampleconfig.json
- Adds configurable FPS counter.
- Makes the IP display configurable as well
=> Adds FPS display

Includes/config.hpp, Includes/ftpConnection.cpp, Includes/ftpConnection.h, Includes/ftpServer.cpp, Includes/menu.hpp, Includes/networking.cpp, Includes/subAppRouter.cpp, Includes/timeMenu.cpp
Suppresses the JSON warnings and fixes various unused vars/override warnings to improve #118.
=> codestyle: Fixes/suppresses some warnings.

.gitignore
=> codestyle: Adds .DS_Store to gitignore.

CMakeLists.txt, Includes/audioMenu.cpp, Includes/config.cpp, Includes/config.hpp, Includes/eeprom.hpp, Includes/infoLog.cpp, Includes/infoLog.h, Includes/langMenu.cpp, Includes/menu.cpp, Includes/menu.hpp, Includes/networkManager.cpp, Includes/networkManager.h, Includes/settingsMenu.cpp, Includes/subAppRouter.cpp, Includes/subAppRouter.h, Includes/timeMenu.cpp, Includes/videoMenu.cpp, Includes/xbeLauncher.cpp, Includes/xbeScanner.cpp, Includes/xbeScanner.h, README.md, main.cpp
Partially addresses #126.
I'm not sure what functionality is expected to work in a linux build, so I've mostly just `#ifdef`'ed out things that are directly dependent on the nxdk. It looks like CMake hasn't worked for over a year, so some of the changes outside my recent PRs are best-guesses.
=> linux: Gets CMake linux build working again.

.github/workflows/build.yml
Fixes #116 
Note: PR #128 has an example of the action catching some (intentionally introduced) errors.
=> Adds workflow for clang-format compliance.

.github/workflows/build-linux.yml, CMakeLists.txt, Includes/audioMenu.cpp, Includes/config.cpp, Includes/config.hpp, Includes/eeprom.hpp, Includes/infoLog.cpp, Includes/infoLog.h, Includes/langMenu.cpp, Includes/menu.cpp, Includes/menu.hpp, Includes/networkManager.cpp, Includes/networkManager.h, Includes/settingsMenu.cpp, Includes/subAppRouter.cpp, Includes/subAppRouter.h, Includes/timeMenu.cpp, Includes/videoMenu.cpp, Includes/xbeLauncher.cpp, Includes/xbeScanner.cpp, Includes/xbeScanner.h, README.md, main.cpp
Addresses the remainder of #126 (keeping the Linux build working once #127 is merged)
=> Adds workflow for linux target

Includes/xbeScanner.cpp
I figure this might be useful in general to see how it behaves in real world scenarios.
=> debug: Adds debug info on XBE scanning.

Sources/ftpConnection.cpp, Sources/menu.cpp
=> paths: Use partition address instead of mountpoint for DVD access
